obj-m += chess.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

l:
	sudo insmod chess.ko

u:
	sudo rmmod chess
